---
appveyor.yml:
  delete: true
.gitignore:
  paths:
    - /[Bb]ackup*/
    - /.devcontainer/
    - /.gitlab-ci.yml
    - /.travis.yml
    - /.vscode/
    - /appveyor.yml
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
.devcontainer:
  delete: true
.vscode:
  delete: true
.pdkignore:
  paths:
    - /[Bb]ackup*/
    - /provision.yaml
    - /.github
    - /pdk.yaml
Gemfile:
  unmanaged: false
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
    ':test':
      - gem: 'puppet_metadata'
        version: '~> 2.0'
      - gem: 'puppet-blacksmith'
      - gem: 'ed25519'
        version:
          - '>= 1.2'
          - '< 2.0'
        require: false
      - gem: 'bcrypt_pbkdf'
        version:
          - '>= 1.0'
          - '< 2.0'
        require: false
Rakefile:
  requires:
      - require: puppet_blacksmith/rake_tasks
        conditional: "Gem.loaded_specs.key? 'puppet-blacksmith'"
spec/spec_helper.rb:
  coverage_report: true
  spec_overrides:
    - 'RSpec.configure do |c|'
    - '  c.facter_implementation = :rspec'
    - 'end'
    - "require 'puppet_blacksmith/rake_tasks' if Gem.loaded_specs.key? 'puppet-blacksmith'"
